name: Poetry

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  poetry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
      - uses: narumiruna/setup-poetry-action@main
        with:
          cache: true
      - run: poetry --version
